import { LinkItem, AutoAddedLinkRecord, AutoSyncHistoryEntry } from '../types';
import { migrateLink } from './dataMigration';
import { deduplicateLinks } from './dedup';
import { getLinkBadges } from './badgeManager';

export interface AutoSyncConfig {
  isEnabled: boolean;
  frequency: 'startup' | 'hourly' | 'daily';
  lastSyncTime: number;
  totalAutoAdded: number;
  syncHistory: AutoSyncHistoryEntry[];
  allAutoAddedLinks?: AutoAddedLinkRecord[];
}

export const CATEGORY_NAMES_MAP: Record<string, string> = {
  movies: 'Movies & Shows',
  anime: 'Anime & Cartoons',
  manga: 'Manga & Comics',
  livetv: 'Live TV & Sports',
  paid: 'Paid & Official',
  apps: 'Apps & APKs',
  telegram: 'Telegram Channels',
  tech: 'Tech & AI Tools',
  books: 'Books & Research',
  '18+': '18+ & Mature',
  adult: '18+ & Mature',
};

export function getCategoryDisplayName(cat?: string): string {
  if (!cat) return 'General';
  return CATEGORY_NAMES_MAP[cat.toLowerCase()] || cat.charAt(0).toUpperCase() + cat.slice(1);
}

const STORAGE_KEY_AUTOSYNC = 'linkbox_autosync_v2';

export const DEFAULT_AUTOSYNC_CONFIG: AutoSyncConfig = {
  isEnabled: true,
  frequency: 'startup',
  lastSyncTime: 0,
  totalAutoAdded: 0,
  syncHistory: [],
  allAutoAddedLinks: [],
};

// Rich repository of global & regional links for continuous auto-updates
export const WORLD_LINKS_REGISTRY: LinkItem[] = [
  // =========================================================================
  // 18+ & MATURE (OFFICIAL OTT, APPS, DESHI, HENTAI & ADULT STREAMING)
  // =========================================================================
  {
    id: 'auto-18p-ullu',
    title: 'Ullu Originals OTT & App',
    url: 'https://ullu.app',
    domain: 'ullu.app',
    category: '18+',
    badge: 'Official',
    logoText: 'ULLU',
    logoColor: '#e11d48',
    logoBg: '#4c0519',
    description: 'Official Indian 18+ web series OTT with exclusive Hindi drama episodes, romance and mobile APK player.',
    tags: ['18+', 'Ullu', 'Deshi', 'Official', 'App', 'Web Series', 'India'],
    regions: ['India', 'Global'],
    clicks: 22400,
    status: 'active',
  },
  {
    id: 'auto-18p-altt',
    title: 'ALTT Mature Originals',
    url: 'https://altt.co.in',
    domain: 'altt.co.in',
    category: '18+',
    badge: 'Official',
    logoText: 'ALTT',
    logoColor: '#f43f5e',
    logoBg: '#3b0764',
    description: 'Balaji official adult web series, romantic suspense thriller stories and uncut Hindi cinema.',
    tags: ['18+', 'ALTT', 'Deshi', 'Official', 'Web Series', 'India'],
    regions: ['India', 'Global'],
    clicks: 18900,
    status: 'active',
  },
  {
    id: 'auto-18p-kooku',
    title: 'Kooku Deshi OTT & APK',
    url: 'https://kooku.app',
    domain: 'kooku.app',
    category: '18+',
    badge: 'App',
    logoText: 'KOOKU',
    logoColor: '#ef4444',
    logoBg: '#271217',
    description: 'Official Indian micro-drama app featuring Desi romance originals, short stories and regional episodes.',
    tags: ['18+', 'Kooku', 'Deshi', 'App', 'Streaming', 'India'],
    regions: ['India', 'Global'],
    clicks: 15300,
    status: 'active',
  },
  {
    id: 'auto-18p-primeshots',
    title: 'PrimeShots 18+ Streaming App',
    url: 'https://primeshots.app',
    domain: 'primeshots.app',
    category: '18+',
    badge: 'App',
    logoText: 'PRIMESHOTS',
    logoColor: '#fb923c',
    logoBg: '#431407',
    description: 'Indian bold romance episodes, exclusive web releases, premium short cinema and dedicated mobile APK.',
    tags: ['18+', 'PrimeShots', 'Deshi', 'App', 'Web Series', 'India'],
    regions: ['India', 'Global'],
    clicks: 13800,
    status: 'active',
  },
  {
    id: 'auto-18p-rabbit',
    title: 'Rabbit Movies 18+ Originals',
    url: 'https://rabbitmovies.com',
    domain: 'rabbitmovies.com',
    category: '18+',
    badge: '18+',
    logoText: 'Rabbit Movies',
    logoColor: '#f59e0b',
    logoBg: '#451a03',
    description: 'Popular Hindi Desi erotic thriller web series, unrated drama and romantic episodes streaming.',
    tags: ['18+', 'Rabbit Movies', 'Deshi', 'Web Series', 'India'],
    regions: ['India', 'Global'],
    clicks: 12100,
    status: 'active',
  },
  {
    id: 'auto-18p-voovi',
    title: 'Voovi OTT & Romantic Shorts',
    url: 'https://voovi.app',
    domain: 'voovi.app',
    category: '18+',
    badge: 'App',
    logoText: 'VOOVI',
    logoColor: '#ec4899',
    logoBg: '#500724',
    description: 'Dedicated Indian romantic short drama platform and mobile app for bold Desi stories.',
    tags: ['18+', 'Voovi', 'Deshi', 'App', 'India'],
    regions: ['India', 'Global'],
    clicks: 11400,
    status: 'active',
  },
  {
    id: 'auto-18p-hunters',
    title: 'Hunters 18+ OTT App',
    url: 'https://hunters.co.in',
    domain: 'hunters.co.in',
    category: '18+',
    badge: 'App',
    logoText: 'HUNTERS',
    logoColor: '#dc2626',
    logoBg: '#450a0a',
    description: 'Indian mature web series network with fast streaming servers and Android APK support.',
    tags: ['18+', 'Hunters', 'Deshi', 'App', 'India'],
    regions: ['India', 'Global'],
    clicks: 9800,
    status: 'active',
  },
  {
    id: 'auto-18p-desicinema',
    title: 'DesiCinema 18+ Uncensored',
    url: 'https://desicinema.tv/genre/18/',
    domain: 'desicinema.tv',
    category: '18+',
    badge: 'HD',
    logoText: 'DesiCinema',
    logoColor: '#3b82f6',
    logoBg: '#1e3a8a',
    description: 'Unofficial streaming collection of Indian 18+ uncut cinema, OTT series and regional adult releases.',
    tags: ['18+', 'DesiCinema', 'Deshi', 'HD', 'India'],
    regions: ['India', 'Global'],
    clicks: 16700,
    status: 'active',
  },
  {
    id: 'auto-18p-adultprime',
    title: 'AdultPrime HD Hindi Series',
    url: 'https://adultprime.in',
    domain: 'adultprime.in',
    category: '18+',
    badge: 'HD',
    logoText: 'AdultPrime',
    logoColor: '#8b5cf6',
    logoBg: '#2e1065',
    description: 'Massive archive of Hindi 18+ web series, Desi erotica, romantic episodes and unrated films in 1080p.',
    tags: ['18+', 'AdultPrime', 'Deshi', 'HD', 'India'],
    regions: ['India', 'Global'],
    clicks: 14500,
    status: 'active',
  },
  {
    id: 'auto-18p-moviesflix18',
    title: 'MoviesFlix 18+ Dual Audio Hub',
    url: 'https://moviesflix.co/category/18-movies/',
    domain: 'moviesflix.co',
    category: '18+',
    badge: '4K UHD',
    logoText: 'MoviesFlix 18+',
    logoColor: '#10b981',
    logoBg: '#064e3b',
    description: 'Hollywood and international 18+ erotic movies with Hindi Dual Audio in 1080p and 4K Ultra HD.',
    tags: ['18+', 'MoviesFlix', 'Dual Audio', '4K', 'Global'],
    regions: ['India', 'Global'],
    clicks: 17800,
    status: 'active',
  },
  {
    id: 'auto-18p-vegamovies18',
    title: 'VegaMovies 18+ Hindi Dubbed',
    url: 'https://vegamovies.im/category/18-adult-movies/',
    domain: 'vegamovies.im',
    category: '18+',
    badge: 'HD',
    logoText: 'VegaMovies 18+',
    logoColor: '#06b6d4',
    logoBg: '#083344',
    description: 'Direct download & streaming of 18+ adult web series, South and Hollywood unrated movies in Hindi.',
    tags: ['18+', 'VegaMovies', 'Hindi Dubbed', '18+', 'India'],
    regions: ['India', 'Global'],
    clicks: 19200,
    status: 'active',
  },
  {
    id: 'auto-18p-katmoviehd18',
    title: 'KatmovieHD 18+ Uncut Cinema',
    url: 'https://katmoviehd.to/category/18-adult-movies/',
    domain: 'katmoviehd.to',
    category: '18+',
    badge: 'HD',
    logoText: 'KatmovieHD 18+',
    logoColor: '#f97316',
    logoBg: '#431407',
    description: 'High definition 18+ uncut adult movies, TV series and international cinema with English and Hindi audio.',
    tags: ['18+', 'KatmovieHD', 'Uncut', '18+', 'Global'],
    regions: ['India', 'Global'],
    clicks: 16100,
    status: 'active',
  },
  {
    id: 'auto-18p-bolly4u18',
    title: 'Bolly4u 18+ Desi Releases',
    url: 'https://bolly4u.org/category/18-adult-movies/',
    domain: 'bolly4u.org',
    category: '18+',
    badge: '18+',
    logoText: 'Bolly4u 18+',
    logoColor: '#eab308',
    logoBg: '#422006',
    description: 'Indian Desi B-grade adult films, OTT unrated series and romantic short clips in 720p HD.',
    tags: ['18+', 'Bolly4u', 'Deshi', '18+', 'India'],
    regions: ['India', 'Global'],
    clicks: 11900,
    status: 'active',
  },
  {
    id: 'auto-18p-18flixhub',
    title: '18FlixHub Hindi Erotic Series',
    url: 'https://18flixhub.com',
    domain: '18flixhub.com',
    category: '18+',
    badge: '18+',
    logoText: '18FlixHub',
    logoColor: '#a855f7',
    logoBg: '#3b0764',
    description: 'Streaming portal for latest Hindi 18+ web series, uncut romance and independent short films.',
    tags: ['18+', '18FlixHub', 'Deshi', 'HD', 'India'],
    regions: ['India', 'Global'],
    clicks: 10500,
    status: 'active',
  },
  {
    id: 'auto-18p-hanime',
    title: 'Hanime.tv HD Hentai',
    url: 'https://hanime.tv',
    domain: 'hanime.tv',
    category: '18+',
    badge: 'Hentai',
    logoText: 'Hanime.tv',
    logoColor: '#f43f5e',
    logoBg: '#4c0519',
    description: 'World leading 1080p full HD uncensored anime hentai streaming network with multi-server cloud playback.',
    tags: ['18+', 'Hentai', 'Hanime', 'Anime 18+', 'HD 1080p', 'Japan'],
    regions: ['Japan', 'Global'],
    clicks: 42000,
    status: 'active',
  },
  {
    id: 'auto-18p-hanime-app',
    title: 'Hanime Android App APK',
    url: 'https://hanime.tv/download',
    domain: 'hanime.tv',
    category: 'apps',
    badge: 'App',
    logoText: 'Hanime App',
    logoColor: '#e11d48',
    logoBg: '#4c0519',
    description: 'Official Hanime Android application APK for streaming 1080p uncensored hentai anime on mobile.',
    tags: ['18+', 'Hentai', 'Hanime', 'App', 'APK', 'Android'],
    regions: ['Japan', 'Global'],
    clicks: 28700,
    status: 'active',
  },
  {
    id: 'auto-18p-nhentai',
    title: 'NHentai Doujinshi Library',
    url: 'https://nhentai.net',
    domain: 'nhentai.net',
    category: '18+',
    badge: 'Hentai',
    logoText: 'nHentai',
    logoColor: '#ef4444',
    logoBg: '#271217',
    description: 'The ultimate digital Japanese doujinshi, 18+ manga reader and translated scanlation archive.',
    tags: ['18+', 'Hentai', 'NHentai', 'Doujinshi', 'Manga', 'Japan'],
    regions: ['Japan', 'Global'],
    clicks: 39500,
    status: 'active',
  },
  {
    id: 'auto-18p-ehentai',
    title: 'E-Hentai Galleries',
    url: 'https://e-hentai.org',
    domain: 'e-hentai.org',
    category: '18+',
    badge: 'Hentai',
    logoText: 'E-Hentai',
    logoColor: '#6366f1',
    logoBg: '#1e1b4b',
    description: 'World largest community driven Japanese doujinshi, manga and art gallery archive with tagging.',
    tags: ['18+', 'Hentai', 'E-Hentai', 'Manga', 'Doujinshi'],
    regions: ['Japan', 'Global'],
    clicks: 31200,
    status: 'active',
  },
  {
    id: 'auto-18p-hentaihaven',
    title: 'HentaiHaven XXX',
    url: 'https://hentaihaven.xxx',
    domain: 'hentaihaven.xxx',
    category: '18+',
    badge: 'Hentai',
    logoText: 'HentaiHaven',
    logoColor: '#ec4899',
    logoBg: '#500724',
    description: 'Classic & modern English subbed anime hentai video archive with high speed streaming.',
    tags: ['18+', 'Hentai', 'HentaiHaven', 'Subbed', 'Japan'],
    regions: ['Japan', 'Global'],
    clicks: 26400,
    status: 'active',
  },
  {
    id: 'auto-18p-hentaifox',
    title: 'HentaiFox Doujinshi & Manga',
    url: 'https://hentaifox.com',
    domain: 'hentaifox.com',
    category: '18+',
    badge: 'Hentai',
    logoText: 'HentaiFox',
    logoColor: '#f97316',
    logoBg: '#431407',
    description: 'Free doujinshi and translated color adult manga reader with fast chapter pagination.',
    tags: ['18+', 'Hentai', 'HentaiFox', 'Manga', 'Japan'],
    regions: ['Japan', 'Global'],
    clicks: 19800,
    status: 'active',
  },
  {
    id: 'auto-18p-hentaimama',
    title: 'HentaiMama Uncensored Stream',
    url: 'https://hentaimama.io',
    domain: 'hentaimama.io',
    category: '18+',
    badge: 'Hentai',
    logoText: 'HentaiMama',
    logoColor: '#8b5cf6',
    logoBg: '#2e1065',
    description: 'Fast streaming platform for latest uncensored anime hentai releases in 1080p and 720p.',
    tags: ['18+', 'Hentai', 'HentaiMama', 'HD', 'Japan'],
    regions: ['Japan', 'Global'],
    clicks: 22100,
    status: 'active',
  },
  {
    id: 'auto-18p-pornhub',
    title: 'Pornhub HD Official',
    url: 'https://www.pornhub.com',
    domain: 'pornhub.com',
    category: '18+',
    badge: 'Official',
    logoText: 'Pornhub',
    logoColor: '#f59e0b',
    logoBg: '#18181b',
    description: 'World largest adult streaming video community with HD 1080p videos, verified creators and mobile player.',
    tags: ['18+', 'Pornhub', 'Official', 'HD 1080p', 'Global'],
    regions: ['Global', 'USA'],
    clicks: 65000,
    status: 'active',
  },
  {
    id: 'auto-18p-xvideos',
    title: 'XVideos Official Network',
    url: 'https://www.xvideos.com',
    domain: 'xvideos.com',
    category: '18+',
    badge: 'Free',
    logoText: 'XVideos',
    logoColor: '#dc2626',
    logoBg: '#18181b',
    description: 'Global free adult entertainment portal with billions of video streams, categories and mobile site.',
    tags: ['18+', 'XVideos', 'Free', 'HD', 'Global'],
    regions: ['Global', 'France', 'USA'],
    clicks: 58000,
    status: 'active',
  },
  {
    id: 'auto-18p-spankbang',
    title: 'SpankBang 4K Ultra Stream',
    url: 'https://spankbang.com',
    domain: 'spankbang.com',
    category: '18+',
    badge: '4K UHD',
    logoText: 'SpankBang',
    logoColor: '#38bdf8',
    logoBg: '#082f49',
    description: 'Ultra fast adult streaming network supporting 4K Ultra HD, 1080p 60FPS video playback and downloads.',
    tags: ['18+', 'SpankBang', '4K UHD', 'HD', 'Global'],
    regions: ['Global', 'USA'],
    clicks: 44000,
    status: 'active',
  },
  {
    id: 'auto-18p-xnxx',
    title: 'XNXX World Adult',
    url: 'https://www.xnxx.com',
    domain: 'xnxx.com',
    category: '18+',
    badge: 'Free',
    logoText: 'XNXX',
    logoColor: '#3b82f6',
    logoBg: '#18181b',
    description: 'Worldwide popular free adult video streaming portal with millions of short and full length clips.',
    tags: ['18+', 'XNXX', 'Free', 'Global'],
    regions: ['Global', 'France'],
    clicks: 51000,
    status: 'active',
  },
  {
    id: 'auto-18p-redtube',
    title: 'RedTube HD Streaming',
    url: 'https://www.redtube.com',
    domain: 'redtube.com',
    category: '18+',
    badge: 'Official',
    logoText: 'RedTube',
    logoColor: '#ef4444',
    logoBg: '#18181b',
    description: 'High definition adult entertainment platform featuring studio releases and amateur community videos.',
    tags: ['18+', 'RedTube', 'Official', 'HD', 'Global'],
    regions: ['Global', 'USA'],
    clicks: 33000,
    status: 'active',
  },
  {
    id: 'auto-18p-brazzers',
    title: 'Brazzers Premium 4K',
    url: 'https://www.brazzers.com',
    domain: 'brazzers.com',
    category: '18+',
    badge: 'Official',
    logoText: 'Brazzers',
    logoColor: '#fbbf24',
    logoBg: '#18181b',
    description: 'Official premium HD and 4K adult cinema network with exclusive episodic series and high quality productions.',
    tags: ['18+', 'Brazzers', 'Official', 'Premium', 'Paid', '4K'],
    regions: ['Global', 'USA', 'Canada'],
    clicks: 29500,
    status: 'active',
  },
  {
    id: 'auto-18p-eporner',
    title: 'Eporner 4K 60FPS Ultra',
    url: 'https://www.eporner.com',
    domain: 'eporner.com',
    category: '18+',
    badge: '4K UHD',
    logoText: 'Eporner',
    logoColor: '#10b981',
    logoBg: '#064e3b',
    description: 'High bitrate 4K Ultra HD and 1080p 60FPS adult streaming portal with zero compression and fast CDN.',
    tags: ['18+', 'Eporner', '4K UHD', 'HD', 'Global'],
    regions: ['Global'],
    clicks: 27800,
    status: 'active',
  },

  // =========================================================================
  // ANIMESALT (ANIME SALT) ALL MOVIES & STREAMING PORTALS
  // =========================================================================
  {
    id: 'auto-ani-animesalt-movies',
    title: 'AnimeSalt Movies Hub',
    url: 'https://animesalt.me/movies',
    domain: 'animesalt.me',
    category: 'anime',
    badge: 'Movie',
    logoText: 'AnimeSalt',
    logoColor: '#cbd5e1',
    logoBg: '#1e293b',
    description: 'Complete collection of Anime blockbuster movies, Hindi Dubbed anime films & subbed specials with zero buffering on AnimeSalt.',
    tags: ['AnimeSalt', 'Anime Movies', 'Hindi Dubbed', 'Subbed', 'HD', 'India', 'Global'],
    regions: ['India', 'Global', 'Japan'],
    clicks: 14800,
    status: 'active',
  },
  {
    id: 'auto-ani-animesalt-hindi',
    title: 'AnimeSalt Hindi Dubbed Cinema',
    url: 'https://animesalt.me/hindi-dubbed',
    domain: 'animesalt.me',
    category: 'anime',
    badge: 'Dubbed',
    logoText: 'AnimeSalt',
    logoColor: '#f97316',
    logoBg: '#431407',
    description: 'Watch all trending Anime films, OVA specials and multi-season cinema in Hindi Audio on AnimeSalt high-speed servers.',
    tags: ['AnimeSalt', 'Hindi Dubbed', 'Anime Movies', 'HD 1080p', 'India'],
    regions: ['India', 'Global'],
    clicks: 16200,
    status: 'active',
  },
  {
    id: 'auto-ani-animesalt-main',
    title: 'AnimeSalt Ultra Streaming',
    url: 'https://animesalt.me',
    domain: 'animesalt.me',
    category: 'anime',
    badge: 'Anime',
    logoText: 'AnimeSalt',
    logoColor: '#38bdf8',
    logoBg: '#0f172a',
    description: 'Minimalist anime player with custom resolution selection, multi-server anime movies and series streaming.',
    tags: ['AnimeSalt', 'Anime', 'Subbed', 'Dubbed', 'Fast', 'India', 'Global'],
    regions: ['India', 'Global', 'Japan'],
    clicks: 18500,
    status: 'active',
  },
  {
    id: 'auto-ani-animesalt-cc',
    title: 'AnimeSalt CC Fast Mirror',
    url: 'https://animesalt.cc',
    domain: 'animesalt.cc',
    category: 'anime',
    badge: 'Anime',
    logoText: 'AnimeSalt CC',
    logoColor: '#a855f7',
    logoBg: '#2e1065',
    description: 'High-speed cloud mirror for AnimeSalt anime movies, OVA episodes and ongoing seasonal releases.',
    tags: ['AnimeSalt', 'Mirror', 'Anime Movies', 'Fast', 'Global'],
    regions: ['India', 'Global'],
    clicks: 11200,
    status: 'active',
  },
  {
    id: 'auto-ani-animesalt-in',
    title: 'AnimeSalt India Portal',
    url: 'https://animesalt.in',
    domain: 'animesalt.in',
    category: 'anime',
    badge: 'Dubbed',
    logoText: 'AnimeSalt IN',
    logoColor: '#ef4444',
    logoBg: '#450a0a',
    description: 'Indian dedicated portal for AnimeSalt anime movie downloads and Hindi dubbed stream links.',
    tags: ['AnimeSalt', 'India', 'Anime Movies', 'Hindi', 'Dubbed'],
    regions: ['India'],
    clicks: 12900,
    status: 'active',
  },
  {
    id: 'auto-ani-animesalt-to',
    title: 'AnimeSalt TO Cloud Hub',
    url: 'https://animesalt.to',
    domain: 'animesalt.to',
    category: 'anime',
    badge: 'Anime',
    logoText: 'AnimeSalt TO',
    logoColor: '#10b981',
    logoBg: '#064e3b',
    description: 'Fast global CDN mirror for AnimeSalt anime movies and multi-audio anime series.',
    tags: ['AnimeSalt', 'Anime Movies', 'Global', 'Cloud Stream'],
    regions: ['Global', 'Japan'],
    clicks: 9800,
    status: 'active',
  },
  {
    id: 'auto-ani-animesalt-app',
    title: 'AnimeSalt Android Player APK',
    url: 'https://animesalt.me/app',
    domain: 'animesalt.me',
    category: 'apps',
    badge: 'App',
    logoText: 'AnimeSalt APK',
    logoColor: '#3b82f6',
    logoBg: '#1e3a8a',
    description: 'Official AnimeSalt Android App APK to stream and download anime movies with Picture-in-Picture.',
    tags: ['AnimeSalt', 'App', 'APK', 'Android', 'Anime Movies', 'Player'],
    regions: ['India', 'Global'],
    clicks: 15400,
    status: 'active',
  },
  {
    id: 'auto-ani-animesalt-tg',
    title: 'AnimeSalt Official Telegram',
    url: 'https://t.me/animesaltofficial',
    domain: 't.me',
    category: 'telegram',
    badge: 'Telegram',
    logoText: 'AnimeSalt TG',
    logoColor: '#0ea5e9',
    logoBg: '#082f49',
    description: 'Official Telegram channel for AnimeSalt direct Google Drive anime movie links and instant episode drops.',
    tags: ['AnimeSalt', 'Telegram', 'Direct Links', 'Anime Movies', 'Drive'],
    regions: ['India', 'Global'],
    clicks: 13600,
    status: 'active',
  },

  // =========================================================================
  // INDIA (IN)
  // =========================================================================
  {
    id: 'auto-in-jiocinema',
    title: 'JioCinema Sports & HBO',
    url: 'https://www.jiocinema.com',
    domain: 'jiocinema.com',
    category: 'paid',
    badge: 'Official',
    logoText: 'JioCinema',
    logoColor: '#e11d48',
    logoBg: '#4c0519',
    description: 'IPL live streaming, HBO originals, Peacock series and Indian blockbuster movies.',
    tags: ['India', 'JioCinema', 'IPL', 'HBO', 'Official'],
    regions: ['India', 'Global'],
    clicks: 14200,
    status: 'active',
  },
  {
    id: 'auto-in-bollyflix',
    title: 'BollyFlix HD',
    url: 'https://bollyflix.city',
    domain: 'bollyflix.city',
    category: 'movies',
    badge: '4K UHD',
    logoText: 'BollyFlix',
    logoColor: '#f59e0b',
    logoBg: '#451a03',
    description: 'Bollywood, Dual Audio 1080p and 4K Ultra HD movies download & streaming.',
    tags: ['India', 'Bollywood', 'Dual Audio', '4K UHD', 'Hindi'],
    regions: ['India', 'Global'],
    clicks: 8700,
    status: 'active',
  },
  {
    id: 'auto-in-cinemavilla',
    title: 'CinemaVilla South',
    url: 'https://cinemavilla.lat',
    domain: 'cinemavilla.lat',
    category: 'movies',
    badge: 'HD',
    logoText: 'CinemaVilla',
    logoColor: '#3b82f6',
    logoBg: '#1e3a8a',
    description: 'Malayalam, Tamil, Telugu and Kannada latest releases with subtitles.',
    tags: ['India', 'South Movies', 'Malayalam', 'Tamil', 'HD'],
    regions: ['India', 'Global'],
    clicks: 6500,
    status: 'active',
  },
  {
    id: 'auto-in-kannadaplay',
    title: 'KannadaPlay Online',
    url: 'https://kannadaplay.com',
    domain: 'kannadaplay.com',
    category: 'movies',
    badge: 'Movie',
    logoText: 'KannadaPlay',
    logoColor: '#ef4444',
    logoBg: '#450a0a',
    description: 'Kannada cinema, Sandalwood classics and regional comedy shows.',
    tags: ['India', 'Kannada', 'Sandalwood', 'Regional Cinema'],
    regions: ['India'],
    clicks: 4300,
    status: 'active',
  },
  {
    id: 'auto-in-ddfree',
    title: 'DD Free Dish Live',
    url: 'https://prasarbharati.gov.in',
    domain: 'prasarbharati.gov.in',
    category: 'livetv',
    badge: 'Official',
    logoText: 'Doordarshan',
    logoColor: '#059669',
    logoBg: '#064e3b',
    description: 'National public broadcaster of India, DD Sports, DD News and regional channels.',
    tags: ['India', 'Doordarshan', 'DD Sports', 'Live TV', 'Official'],
    regions: ['India'],
    clicks: 5600,
    status: 'active',
  },

  // =========================================================================
  // UNITED STATES / GLOBAL
  // =========================================================================
  {
    id: 'auto-us-criterion',
    title: 'The Criterion Channel',
    url: 'https://www.criterionchannel.com',
    domain: 'criterionchannel.com',
    category: 'paid',
    badge: 'Official',
    logoText: 'Criterion',
    logoColor: '#ffffff',
    logoBg: '#18181b',
    description: 'Classics and discoveries from around the world, auteur cinema and curated film series.',
    tags: ['USA', 'Criterion', 'Classic Cinema', 'Art House', 'Official'],
    regions: ['USA', 'Global'],
    clicks: 7600,
    status: 'active',
  },
  {
    id: 'auto-us-mubi',
    title: 'MUBI Cinema',
    url: 'https://mubi.com',
    domain: 'mubi.com',
    category: 'paid',
    badge: 'Official',
    logoText: 'MUBI',
    logoColor: '#38bdf8',
    logoBg: '#082f49',
    description: 'Hand-picked cinema from visionary directors and emerging filmmakers worldwide.',
    tags: ['Global', 'MUBI', 'Independent Cinema', 'Film Festival', 'Official'],
    regions: ['Global', 'USA', 'France', 'UK', 'Germany'],
    clicks: 8100,
    status: 'active',
  },
  {
    id: 'auto-us-soap2day',
    title: 'Soap2Day HD',
    url: 'https://soap2day.pe',
    domain: 'soap2day.pe',
    category: 'movies',
    badge: 'Movie',
    logoText: 'Soap2Day',
    logoColor: '#ec4899',
    logoBg: '#500724',
    description: 'Fast streaming platform for latest blockbuster movies and ongoing TV series.',
    tags: ['Movies', 'Streaming', 'Soap2Day', 'Fast'],
    regions: ['Global', 'USA'],
    clicks: 11400,
    status: 'active',
  },
  {
    id: 'auto-us-freemoviesfull',
    title: 'FreeMoviesFull',
    url: 'https://freemoviesfull.cc',
    domain: 'freemoviesfull.cc',
    category: 'movies',
    badge: 'HD',
    logoText: 'FreeMoviesFull',
    logoColor: '#a855f7',
    logoBg: '#3b0764',
    description: 'Massive library of Hollywood and international titles in 1080p full HD.',
    tags: ['Movies', 'Free Movies', 'Full HD', 'Hollywood'],
    regions: ['Global', 'USA'],
    clicks: 6900,
    status: 'active',
  },
  {
    id: 'auto-us-internetarchive',
    title: 'Internet Archive Movies',
    url: 'https://archive.org/details/movies',
    domain: 'archive.org',
    category: 'movies',
    badge: 'Official',
    logoText: 'Archive.org',
    logoColor: '#6366f1',
    logoBg: '#1e1b4b',
    description: 'Millions of free digital movies, vintage cinema, open educational videos, and documentaries.',
    tags: ['Archive', 'Public Domain', 'Free', 'Official', 'Preservation'],
    regions: ['Global', 'USA'],
    clicks: 10200,
    status: 'active',
  },

  // =========================================================================
  // JAPAN (JP)
  // =========================================================================
  {
    id: 'auto-jp-tver',
    title: 'TVer Japan',
    url: 'https://tver.jp',
    domain: 'tver.jp',
    category: 'livetv',
    badge: 'Official',
    logoText: 'TVer',
    logoColor: '#0ea5e9',
    logoBg: '#082f49',
    description: 'Official portal for Japanese commercial TV stations (NTV, TV Asahi, TBS, TV Tokyo, Fuji TV).',
    tags: ['Japan', 'TVer', 'Official', 'Japanese Drama', 'Variety Shows'],
    regions: ['Japan'],
    clicks: 7400,
    status: 'active',
  },
  {
    id: 'auto-jp-gogoanime',
    title: 'GogoAnime HD',
    url: 'https://anitaku.to',
    domain: 'anitaku.to',
    category: 'anime',
    badge: 'Anime',
    logoText: 'GogoAnime',
    logoColor: '#f97316',
    logoBg: '#431407',
    description: 'Instant anime episodes updated hourly with English sub and dub servers.',
    tags: ['Anime', 'GogoAnime', 'Subbed', 'Dubbed', 'Fast'],
    regions: ['Japan', 'Global'],
    clicks: 13500,
    status: 'active',
  },
  {
    id: 'auto-jp-nyaa',
    title: 'Nyaa Torrents (Anime)',
    url: 'https://nyaa.si',
    domain: 'nyaa.si',
    category: 'anime',
    badge: '4K UHD',
    logoText: 'Nyaa',
    logoColor: '#10b981',
    logoBg: '#064e3b',
    description: 'The world’s primary database for East Asian anime, raw video, lossless music, and software.',
    tags: ['Japan', 'Anime', 'Lossless', 'Raw', 'P2P'],
    regions: ['Japan', 'Global'],
    clicks: 15200,
    status: 'active',
  },
  {
    id: 'auto-jp-mangakakalot',
    title: 'MangaKakalot',
    url: 'https://mangakakalot.com',
    domain: 'mangakakalot.com',
    category: 'manga',
    badge: 'Manga',
    logoText: 'MangaKakalot',
    logoColor: '#eab308',
    logoBg: '#422006',
    description: 'Read manga online free in high quality with daily chapter releases.',
    tags: ['Manga', 'MangaKakalot', 'Japanese Comics', 'Chapters'],
    regions: ['Japan', 'Global'],
    clicks: 9800,
    status: 'active',
  },

  // =========================================================================
  // SOUTH KOREA (KR)
  // =========================================================================
  {
    id: 'auto-kr-koreasub',
    title: 'KissAsian KDrama',
    url: 'https://kissasian.lu',
    domain: 'kissasian.lu',
    category: 'movies',
    badge: 'Movie',
    logoText: 'KissAsian',
    logoColor: '#f43f5e',
    logoBg: '#4c0519',
    description: 'Top streaming hub for Korean dramas, K-movies, and Asian entertainment with English subtitles.',
    tags: ['Korea', 'K-Drama', 'KissAsian', 'Asian Cinema'],
    regions: ['Korea', 'Global'],
    clicks: 10600,
    status: 'active',
  },
  {
    id: 'auto-kr-toptoon',
    title: 'TopToon Plus',
    url: 'https://toptoonplus.com',
    domain: 'toptoonplus.com',
    category: 'manga',
    badge: 'Official',
    logoText: 'TopToon',
    logoColor: '#dc2626',
    logoBg: '#450a0a',
    description: 'Official global webtoon portal featuring Korean serialized romance, fantasy and action comics.',
    tags: ['Korea', 'TopToon', 'Webtoons', 'Official', 'Manhwa'],
    regions: ['Korea', 'Global'],
    clicks: 6100,
    status: 'active',
  },
  {
    id: 'auto-kr-kbslive',
    title: 'KBS World TV',
    url: 'https://kbsworld.kbs.co.kr',
    domain: 'kbs.co.kr',
    category: 'livetv',
    badge: 'Official',
    logoText: 'KBS World',
    logoColor: '#2563eb',
    logoBg: '#1e3a8a',
    description: 'Official Korean national broadcast channel with live K-Pop, news, and entertainment shows.',
    tags: ['Korea', 'KBS', 'Live TV', 'K-Pop', 'Official'],
    regions: ['Korea', 'Global'],
    clicks: 5800,
    status: 'active',
  },

  // =========================================================================
  // FRANCE (FR)
  // =========================================================================
  {
    id: 'auto-fr-francetv',
    title: 'France.tv Direct',
    url: 'https://www.france.tv',
    domain: 'france.tv',
    category: 'livetv',
    badge: 'Official',
    logoText: 'France.tv',
    logoColor: '#0284c7',
    logoBg: '#082f49',
    description: 'Accédez en direct et en replay aux programmes de France 2, France 3, France 4 et France 5.',
    tags: ['France', 'France.tv', 'Official', 'Direct TV', 'Replay'],
    regions: ['France'],
    clicks: 6200,
    status: 'active',
  },
  {
    id: 'auto-fr-canalplus',
    title: 'Canal+ myCANAL',
    url: 'https://www.canalplus.com',
    domain: 'canalplus.com',
    category: 'paid',
    badge: 'Official',
    logoText: 'Canal+',
    logoColor: '#18181b',
    logoBg: '#09090b',
    description: 'Cinéma ultra-récent, séries originales Création Originale et grands événements sportifs.',
    tags: ['France', 'Canal+', 'Cinéma', 'Séries', 'Premium'],
    regions: ['France', 'Global'],
    clicks: 7900,
    status: 'active',
  },
  {
    id: 'auto-fr-wiflix',
    title: 'Wiflix VF Stream',
    url: 'https://wiflix.voto',
    domain: 'wiflix.voto',
    category: 'movies',
    badge: 'Movie',
    logoText: 'Wiflix',
    logoColor: '#ec4899',
    logoBg: '#500724',
    description: 'Films et séries streaming complet en version française (VF) et VOSTFR sans inscription.',
    tags: ['France', 'Wiflix', 'VF', 'VOSTFR', 'HD'],
    regions: ['France'],
    clicks: 8400,
    status: 'active',
  },

  // =========================================================================
  // GERMANY (DE)
  // =========================================================================
  {
    id: 'auto-de-rtlplus',
    title: 'RTL+ Deutschland',
    url: 'https://plus.rtl.de',
    domain: 'rtl.de',
    category: 'paid',
    badge: 'Official',
    logoText: 'RTL+',
    logoColor: '#ef4444',
    logoBg: '#450a0a',
    description: 'Filme, Serien, Podcasts, Musik und Live-Sport mit der All-in-One Entertainment App.',
    tags: ['Germany', 'RTL+', 'Live Sport', 'Serien', 'Official'],
    regions: ['Germany'],
    clicks: 6700,
    status: 'active',
  },
  {
    id: 'auto-de-kinox',
    title: 'KinoX DE Stream',
    url: 'https://kinox.to',
    domain: 'kinox.to',
    category: 'movies',
    badge: 'HD',
    logoText: 'KinoX',
    logoColor: '#8b5cf6',
    logoBg: '#2e1065',
    description: 'Online Filme und Serien auf Deutsch kostenlos in voller Länge und HD ansehen.',
    tags: ['Germany', 'KinoX', 'Deutsch', 'Filme', 'HD'],
    regions: ['Germany'],
    clicks: 9100,
    status: 'active',
  },

  // =========================================================================
  // SPAIN (ES) & LATAM
  // =========================================================================
  {
    id: 'auto-es-cuevana',
    title: 'Cuevana 3 HD',
    url: 'https://cuevana3.ch',
    domain: 'cuevana3.ch',
    category: 'movies',
    badge: 'Movie',
    logoText: 'Cuevana 3',
    logoColor: '#06b6d4',
    logoBg: '#083344',
    description: 'El portal más popular de películas y series online en audio latino y castellano HD.',
    tags: ['Spain', 'Cuevana', 'Audio Latino', 'Castellano', 'HD'],
    regions: ['Spain', 'Brazil', 'Global'],
    clicks: 14800,
    status: 'active',
  },
  {
    id: 'auto-es-movistar',
    title: 'Movistar Plus+',
    url: 'https://www.movistarplus.es',
    domain: 'movistarplus.es',
    category: 'paid',
    badge: 'Official',
    logoText: 'Movistar+',
    logoColor: '#0284c7',
    logoBg: '#082f49',
    description: 'La mejor oferta de televisión con estrenos de cine, series exclusivas y LaLiga en directo.',
    tags: ['Spain', 'Movistar Plus', 'LaLiga', 'Fútbol', 'Premium'],
    regions: ['Spain'],
    clicks: 6300,
    status: 'active',
  },

  // =========================================================================
  // APPS & UTILITIES
  // =========================================================================
  {
    id: 'auto-app-revanced',
    title: 'ReVanced App',
    url: 'https://revanced.app',
    domain: 'revanced.app',
    category: 'apps',
    badge: 'App',
    logoText: 'ReVanced',
    logoColor: '#3b82f6',
    logoBg: '#1e3a8a',
    description: 'The continuation of Vanced: patch YouTube, Reddit, Twitter, and Spotify with ad-blocking.',
    tags: ['ReVanced', 'Android', 'Ad-Free', 'Open Source', 'FOSS'],
    regions: ['Global'],
    clicks: 14200,
    status: 'active',
  },
  {
    id: 'auto-app-kodi',
    title: 'Kodi Media Center',
    url: 'https://kodi.tv',
    domain: 'kodi.tv',
    category: 'apps',
    badge: 'Official',
    logoText: 'Kodi',
    logoColor: '#0284c7',
    logoBg: '#082f49',
    description: 'Free and open-source cross-platform software media player and entertainment hub.',
    tags: ['Kodi', 'Media Player', 'IPTV', 'Addons', 'Official'],
    regions: ['Global'],
    clicks: 11000,
    status: 'active',
  },
  {
    id: 'auto-app-uptodown',
    title: 'Uptodown App Store',
    url: 'https://www.uptodown.com',
    domain: 'uptodown.com',
    category: 'apps',
    badge: 'App',
    logoText: 'Uptodown',
    logoColor: '#10b981',
    logoBg: '#064e3b',
    description: 'International multiplatform app store specialized in safe Android and desktop downloads.',
    tags: ['Uptodown', 'App Store', 'Android APK', 'Safe Download'],
    regions: ['Global', 'Spain', 'Brazil'],
    clicks: 9400,
    status: 'active',
  },

  // =========================================================================
  // ADDITIONAL AUTO-SYNC EXPANSIONS: MOVIES, MANGA, ANIME, 18+ BRANCHES
  // =========================================================================
  {
    id: 'auto-sync-mov-vegamovies',
    title: 'VegaMovies 4K & Dual Audio Cinema',
    url: 'https://vegamovies.im',
    domain: 'vegamovies.im',
    category: 'movies',
    badge: '4K UHD',
    logoText: 'VegaMovies',
    logoColor: '#10b981',
    logoBg: '#064e3b',
    description: 'Fast direct Google Drive download links for 4K UHD, Bollywood hits and Hollywood Dual Audio.',
    tags: ['VegaMovies', 'Bollywood', 'Hollywood', 'Dual Audio', '4K UHD', 'India'],
    regions: ['India', 'Global', 'USA'],
    clicks: 34500,
    status: 'active',
  },
  {
    id: 'auto-sync-mov-katmoviehd',
    title: 'KatmovieHD Multi-Audio Movies',
    url: 'https://katmoviehd.to',
    domain: 'katmoviehd.to',
    category: 'movies',
    badge: 'Dubbed',
    logoText: 'KatmovieHD',
    logoColor: '#f59e0b',
    logoBg: '#451a03',
    description: 'Multi-Audio Dual Hindi Dubbed Hollywood blockbusters, Korean cinema and TV series.',
    tags: ['KatmovieHD', 'Hollywood', 'Bollywood', 'Dual Audio', 'Hindi Dubbed', 'Global'],
    regions: ['India', 'Global', 'USA'],
    clicks: 31200,
    status: 'active',
  },
  {
    id: 'auto-sync-mov-lookmovie2',
    title: 'LookMovie2 HD Cinema',
    url: 'https://lookmovie2.to',
    domain: 'lookmovie2.to',
    category: 'movies',
    badge: 'HD',
    logoText: 'LookMovie2',
    logoColor: '#06b6d4',
    logoBg: '#083344',
    description: 'Fast bufferless Hollywood streaming in 1080p with subtitle sync and rich movie catalog.',
    tags: ['LookMovie', 'Hollywood', 'Global', 'HD 1080p', 'English Subtitles', 'USA'],
    regions: ['Global', 'USA', 'UK', 'India'],
    clicks: 29800,
    status: 'active',
  },
  {
    id: 'auto-sync-mov-dramacool',
    title: 'Dramacool Asian Drama & Cinema',
    url: 'https://dramacool.ch',
    domain: 'dramacool.ch',
    category: 'movies',
    badge: 'HD',
    logoText: 'Dramacool',
    logoColor: '#f43f5e',
    logoBg: '#4c0519',
    description: 'Comprehensive streaming portal for Korean Dramas, Asian cinema and movies with English subs.',
    tags: ['Dramacool', 'KDrama', 'Asian Cinema', 'Korean Movies', 'English Sub', 'Korea', 'Global'],
    regions: ['Korea', 'Global', 'India', 'USA'],
    clicks: 28400,
    status: 'active',
  },
  {
    id: 'auto-sync-ani-animesalt-to',
    title: 'AnimeSalt TO Cloud Hub',
    url: 'https://animesalt.to',
    domain: 'animesalt.to',
    category: 'anime',
    badge: 'Anime',
    logoText: 'AnimeSalt TO',
    logoColor: '#a855f7',
    logoBg: '#3b0764',
    description: 'Ultra fast cloud player with 1080p 60fps streaming for all seasonal anime movies and episodes on AnimeSalt.',
    tags: ['AnimeSalt', 'Anime Movies', 'Cloud Player', '1080p', 'Fast', 'Global'],
    regions: ['Global', 'India', 'Japan'],
    clicks: 21500,
    status: 'active',
  },
  {
    id: 'auto-sync-ani-hianime',
    title: 'HiAnime Zoro Anime Streaming',
    url: 'https://hianime.to',
    domain: 'hianime.to',
    category: 'anime',
    badge: '4K UHD',
    logoText: 'HiAnime',
    logoColor: '#f43f5e',
    logoBg: '#4c0519',
    description: 'Top anime streaming platform with synchronized subtitles, multi-server playback and anime movies.',
    tags: ['HiAnime', 'Zoro', 'Anime', 'Subbed', 'Dubbed', 'Anime Movies', 'Global'],
    regions: ['Global', 'Japan', 'India', 'USA'],
    clicks: 44000,
    status: 'active',
  },
  {
    id: 'auto-sync-ani-animedubhindi',
    title: 'AnimeDubHindi Hub',
    url: 'https://animedubhindi.top',
    domain: 'animedubhindi.top',
    category: 'anime',
    badge: 'Dubbed',
    logoText: 'DubHindi',
    logoColor: '#f97316',
    logoBg: '#431407',
    description: 'Hindi Dubbed Anime episodes and films for Naruto, Dragon Ball, Demon Slayer and One Piece.',
    tags: ['AnimeDubHindi', 'Hindi Dubbed Anime', 'India', 'Anime Movies', 'Naruto'],
    regions: ['India', 'Global'],
    clicks: 26500,
    status: 'active',
  },
  {
    id: 'auto-sync-ani-lucifer-donghua',
    title: 'Lucifer Donghua (Chinese Anime)',
    url: 'https://luciferdonghua.org',
    domain: 'luciferdonghua.org',
    category: 'anime',
    badge: 'Anime',
    logoText: 'Donghua',
    logoColor: '#06b6d4',
    logoBg: '#083344',
    description: 'Premier Chinese 3D anime portal with English subtitles for Soul Land, Perfect World, and Battle Through Heavens.',
    tags: ['Donghua', 'Lucifer Donghua', 'Chinese Anime', 'Soul Land', '3D Anime', 'Global'],
    regions: ['Global', 'China', 'India'],
    clicks: 19800,
    status: 'active',
  },
  {
    id: 'auto-sync-mng-mangadex',
    title: 'MangaDex Open Community Reader',
    url: 'https://mangadex.org',
    domain: 'mangadex.org',
    category: 'manga',
    badge: 'Free',
    logoText: 'MangaDex',
    logoColor: '#f97316',
    logoBg: '#431407',
    description: 'Open-source community manga reader with ad-free scanlations and multi-language translations.',
    tags: ['MangaDex', 'Manga', 'Scanlations', 'Ad-Free', 'Multi-Language', 'Global'],
    regions: ['Global', 'Japan', 'USA', 'India'],
    clicks: 43000,
    status: 'active',
  },
  {
    id: 'auto-sync-mng-asurascans',
    title: 'AsuraScans Action Manhwa Reader',
    url: 'https://asuracomic.net',
    domain: 'asuracomic.net',
    category: 'manga',
    badge: 'HD',
    logoText: 'AsuraScans',
    logoColor: '#8b5cf6',
    logoBg: '#2e1065',
    description: 'High-quality Korean action manhwa, dungeon leveling, cultivation and fantasy webtoons.',
    tags: ['AsuraScans', 'Manhwa', 'Webtoons', 'Solo Leveling', 'Action', 'Korea', 'Global'],
    regions: ['Global', 'Korea', 'USA', 'India'],
    clicks: 39500,
    status: 'active',
  },
  {
    id: 'auto-sync-mng-mangafire',
    title: 'MangaFire Fast HD Reader',
    url: 'https://mangafire.to',
    domain: 'mangafire.to',
    category: 'manga',
    badge: 'HD',
    logoText: 'MangaFire',
    logoColor: '#ef4444',
    logoBg: '#450a0a',
    description: 'Manga & manhwa reading interface with crystal clear scans and automatic chapter sync.',
    tags: ['MangaFire', 'Manga', 'Manhwa', 'HD Scans', 'Fast Reader', 'Global'],
    regions: ['Global', 'Japan', 'USA'],
    clicks: 31000,
    status: 'active',
  },
  {
    id: 'auto-sync-mng-mangaplus',
    title: 'Manga Plus Shonen Jump Official',
    url: 'https://mangaplus.shueisha.co.jp',
    domain: 'mangaplus.shueisha.co.jp',
    category: 'manga',
    badge: 'Official',
    logoText: 'MANGA+',
    logoColor: '#e11d48',
    logoBg: '#4c0519',
    description: 'Official Shonen Jump chapters simultaneously released with Japan for One Piece, JJK, and Chainsaw Man.',
    tags: ['MangaPlus', 'Shueisha', 'Shonen Jump', 'Official', 'One Piece', 'Japan', 'Global'],
    regions: ['Global', 'Japan', 'USA', 'India'],
    clicks: 41200,
    status: 'active',
  },
  {
    id: 'auto-sync-18p-altt',
    title: 'ALTT 18+ Uncut OTT',
    url: 'https://altt.co.in',
    domain: 'altt.co.in',
    category: '18+',
    badge: 'Official',
    logoText: 'ALTT',
    logoColor: '#f43f5e',
    logoBg: '#4c0519',
    description: 'Official Indian OTT with bold Hindi drama, romance web series and uncensored originals.',
    tags: ['ALTT', '18+', 'OTT', 'Desi Drama', 'Indian Web Series', 'India'],
    regions: ['India', 'Global'],
    clicks: 28900,
    status: 'active',
  },
  {
    id: 'auto-sync-18p-kooku',
    title: 'Kooku VIP Originals',
    url: 'https://kooku.app',
    domain: 'kooku.app',
    category: '18+',
    badge: 'App',
    logoText: 'KOOKU',
    logoColor: '#eab308',
    logoBg: '#422006',
    description: 'Indian mature web series platform with trending Hindi episodes, drama and mobile player.',
    tags: ['Kooku', '18+', 'Web Series', 'Desi OTT', 'India'],
    regions: ['India', 'Global'],
    clicks: 26100,
    status: 'active',
  },
  {
    id: 'auto-sync-18p-desicinema',
    title: 'DesiCinema 18+ Uncut Cinema',
    url: 'https://desicinemas.tv/genre/18-plus',
    domain: 'desicinemas.tv',
    category: '18+',
    badge: '18+',
    logoText: 'DesiCinema',
    logoColor: '#ef4444',
    logoBg: '#450a0a',
    description: 'Curated Indian 18+ movies, uncut web series episodes and adult short films.',
    tags: ['DesiCinema', '18+', 'Deshi', 'Bollywood 18+', 'Uncut', 'India'],
    regions: ['India', 'Global'],
    clicks: 33400,
    status: 'active',
  },
  {
    id: 'auto-sync-18p-hanime-apk',
    title: 'Hanime Android Official APK',
    url: 'https://hanime.tv/mobile',
    domain: 'hanime.tv',
    category: '18+',
    badge: 'App',
    logoText: 'HANIME APK',
    logoColor: '#ec4899',
    logoBg: '#500724',
    description: 'Dedicated lightweight Android mobile app for Hanime with offline downloads and 1080p stream.',
    tags: ['Hanime App', '18+', 'Android APK', 'Hentai App', 'Mobile', 'Global'],
    regions: ['Global', 'Japan', 'India', 'USA'],
    clicks: 28400,
    status: 'active',
  },

  // =========================================================================
  // TECH & AI TOOLS (CURATED DEVELOPER & PRODUCTIVITY PLATFORMS)
  // =========================================================================
  {
    id: 'auto-tech-huggingface',
    title: 'Hugging Face AI & Models',
    url: 'https://huggingface.co',
    domain: 'huggingface.co',
    category: 'tech',
    badge: 'Trending',
    logoText: 'HF AI',
    logoColor: '#f59e0b',
    logoBg: '#451a03',
    description: 'The AI community building the future. Download open-source LLMs, diffusion models, and datasets.',
    tags: ['AI', 'Tech', 'HuggingFace', 'Models', 'Python', 'Global'],
    regions: ['Global', 'USA', 'India', 'UK'],
    clicks: 34200,
    status: 'active',
  },
  {
    id: 'auto-tech-perplexity',
    title: 'Perplexity AI Search',
    url: 'https://perplexity.ai',
    domain: 'perplexity.ai',
    category: 'tech',
    badge: 'Popular',
    logoText: 'PERPLEX',
    logoColor: '#06b6d4',
    logoBg: '#083344',
    description: 'Next-generation AI conversational search engine with cited real-time web sources and research mode.',
    tags: ['AI Search', 'Tech', 'Productivity', 'Research', 'Global'],
    regions: ['Global', 'USA', 'India', 'UK'],
    clicks: 41800,
    status: 'active',
  },
  {
    id: 'auto-tech-deepseek',
    title: 'DeepSeek AI Reasoner',
    url: 'https://deepseek.com',
    domain: 'deepseek.com',
    category: 'tech',
    badge: 'NEW',
    logoText: 'DEEPSEEK',
    logoColor: '#3b82f6',
    logoBg: '#1e1b4b',
    description: 'Open-weights reasoning model with high performance code generation and math reasoning.',
    tags: ['DeepSeek', 'AI', 'Coding', 'OpenSource', 'Tech', 'Global'],
    regions: ['Global', 'India', 'USA', 'UK'],
    clicks: 52900,
    status: 'active',
  },
  {
    id: 'auto-tech-phind',
    title: 'Phind AI for Developers',
    url: 'https://phind.com',
    domain: 'phind.com',
    category: 'tech',
    badge: 'Free',
    logoText: 'PHIND',
    logoColor: '#10b981',
    logoBg: '#064e3b',
    description: 'Intelligent search engine crafted specifically for developers with code snippets, technical answers, and documentation.',
    tags: ['Developer', 'AI', 'Coding', 'Search', 'Tech', 'Global'],
    regions: ['Global', 'USA', 'India'],
    clicks: 21300,
    status: 'active',
  },
  {
    id: 'auto-tech-v0',
    title: 'V0 by Vercel UI Builder',
    url: 'https://v0.dev',
    domain: 'v0.dev',
    category: 'tech',
    badge: 'Official',
    logoText: 'V0 DEV',
    logoColor: '#ffffff',
    logoBg: '#000000',
    description: 'Generative user interface engine powering modern web apps with React, Tailwind CSS, and shadcn.',
    tags: ['Vercel', 'UI', 'Frontend', 'React', 'Tech', 'Global'],
    regions: ['Global', 'USA', 'India', 'UK'],
    clicks: 38900,
    status: 'active',
  },
  {
    id: 'auto-tech-cursor',
    title: 'Cursor AI Code Editor',
    url: 'https://cursor.com',
    domain: 'cursor.com',
    category: 'tech',
    badge: 'Trending',
    logoText: 'CURSOR',
    logoColor: '#8b5cf6',
    logoBg: '#2e1065',
    description: 'Next-generation AI editor built on VS Code with seamless multi-file edits and intelligent agent prompt execution.',
    tags: ['IDE', 'Editor', 'AI', 'Coding', 'Tech', 'Global'],
    regions: ['Global', 'USA', 'India', 'UK'],
    clicks: 44100,
    status: 'active',
  },

  // =========================================================================
  // BOOKS & RESEARCH (UNIVERSAL REPOSITORIES, PAPERS & EBOOKS)
  // =========================================================================
  {
    id: 'auto-books-annas-archive',
    title: "Anna's Archive Universal Library",
    url: 'https://annas-archive.org',
    domain: 'annas-archive.org',
    category: 'books',
    badge: 'Popular',
    logoText: 'ANNAS',
    logoColor: '#14b8a6',
    logoBg: '#042f2e',
    description: "The largest truly open library in human history. Mirrored books, papers, comics, and magazines.",
    tags: ['Books', 'PDF', 'Library', 'Research', 'Comics', 'Global'],
    regions: ['Global', 'India', 'USA', 'UK'],
    clicks: 39500,
    status: 'active',
  },
  {
    id: 'auto-books-libgen',
    title: 'Library Genesis (LibGen)',
    url: 'https://libgen.is',
    domain: 'libgen.is',
    category: 'books',
    badge: 'Free',
    logoText: 'LIBGEN',
    logoColor: '#38bdf8',
    logoBg: '#0c4a6e',
    description: 'Free scientific articles, non-fiction and fiction textbooks with direct mirrors and torrent links.',
    tags: ['LibGen', 'Research', 'Books', 'Textbooks', 'Papers', 'Global'],
    regions: ['Global', 'India', 'USA', 'UK'],
    clicks: 48900,
    status: 'active',
  },
  {
    id: 'auto-books-openlibrary',
    title: 'Open Library Internet Archive',
    url: 'https://openlibrary.org',
    domain: 'openlibrary.org',
    category: 'books',
    badge: 'Official',
    logoText: 'OPEN LIB',
    logoColor: '#f97316',
    logoBg: '#431407',
    description: 'Millions of borrowable books and free digitizations backed by the Internet Archive non-profit.',
    tags: ['Open Library', 'Archive', 'Digital Books', 'Ebooks', 'Global'],
    regions: ['Global', 'USA', 'India', 'UK'],
    clicks: 27600,
    status: 'active',
  },
  {
    id: 'auto-books-standardebooks',
    title: 'Standard Ebooks Public Domain',
    url: 'https://standardebooks.org',
    domain: 'standardebooks.org',
    category: 'books',
    badge: 'Free',
    logoText: 'STD EBOOKS',
    logoColor: '#10b981',
    logoBg: '#022c22',
    description: 'Free, carefully formatted, and typographically beautiful public domain books for Kindle, Kobo, and e-readers.',
    tags: ['Standard Ebooks', 'Epub', 'Kindle', 'Classics', 'Global'],
    regions: ['Global', 'USA', 'UK', 'India'],
    clicks: 18200,
    status: 'active',
  },
  {
    id: 'auto-books-gutenberg',
    title: 'Project Gutenberg Archive',
    url: 'https://gutenberg.org',
    domain: 'gutenberg.org',
    category: 'books',
    badge: 'Free',
    logoText: 'GUTENBERG',
    logoColor: '#a855f7',
    logoBg: '#3b0764',
    description: 'Over 70,000 free electronic books and audiobooks of world literature without registration or fee.',
    tags: ['Gutenberg', 'Literature', 'Free Books', 'Ebooks', 'Global'],
    regions: ['Global', 'USA', 'UK', 'India'],
    clicks: 31200,
    status: 'active',
  },

  // =========================================================================
  // TELEGRAM GROUPS & CHANNELS
  // =========================================================================
  {
    id: 'auto-tg-linkbox-official',
    title: 'LinkBox Telegram Community',
    url: 'https://t.me/LinkBoxOfficial',
    domain: 't.me',
    category: 'telegram',
    badge: 'Official',
    logoText: 'TG LINKBOX',
    logoColor: '#0ea5e9',
    logoBg: '#082f49',
    description: 'Direct backup channels, live proxy updates, community requests, and new mirror announcements.',
    tags: ['Telegram', 'LinkBox', 'Updates', 'Mirrors', 'Community', 'Global'],
    regions: ['Global', 'India', 'USA'],
    clicks: 29800,
    status: 'active',
  },
  {
    id: 'auto-tg-movie-hub',
    title: 'Cinema Hub Movie Links & Bot',
    url: 'https://t.me/CinemaHubOfficial',
    domain: 't.me',
    category: 'telegram',
    badge: 'Popular',
    logoText: 'CINEMA TG',
    logoColor: '#38bdf8',
    logoBg: '#0369a1',
    description: 'Fast cloud drive links, multi-audio cinema prints, and direct bot media streams on Telegram.',
    tags: ['Telegram', 'Movies', 'Cinema', 'Dual Audio', 'Fast Links', 'India'],
    regions: ['India', 'Global'],
    clicks: 34500,
    status: 'active',
  }
];

export function getAutoSyncConfig(): AutoSyncConfig {
  try {
    const saved = localStorage.getItem(STORAGE_KEY_AUTOSYNC);
    if (saved) {
      return { ...DEFAULT_AUTOSYNC_CONFIG, ...JSON.parse(saved) };
    }
  } catch (err) {
    console.error('Failed to parse auto sync config:', err);
  }
  return DEFAULT_AUTOSYNC_CONFIG;
}

export function saveAutoSyncConfig(config: AutoSyncConfig): void {
  try {
    localStorage.setItem(STORAGE_KEY_AUTOSYNC, JSON.stringify(config));
  } catch (err) {
    console.error('Failed to save auto sync config:', err);
  }
}

/**
 * Checks for any links from the world registry that haven't been added to the user directory yet.
 */
export function getAvailableNewLinks(currentLinks: LinkItem[], categoryFilter?: string): LinkItem[] {
  const existingDomainAndUrls = new Set(
    currentLinks.map((l) => `${l.domain.toLowerCase()}|${l.url.toLowerCase()}`)
  );
  const existingIds = new Set(currentLinks.map((l) => l.id.toLowerCase()));

  let missingLinks = WORLD_LINKS_REGISTRY.filter((registryLink) => {
    const key = `${registryLink.domain.toLowerCase()}|${registryLink.url.toLowerCase()}`;
    const idKey = registryLink.id.toLowerCase();
    return !existingDomainAndUrls.has(key) && !existingIds.has(idKey);
  });

  if (categoryFilter && categoryFilter !== 'all') {
    const target = categoryFilter.toLowerCase();
    missingLinks = missingLinks.filter((l) => {
      const cat = (l.category || '').toLowerCase();
      if (target === '18+' || target === 'adult') {
        return cat === '18+' || cat === 'adult' || (l.tags || []).some(t => t.toLowerCase() === '18+' || t.toLowerCase() === 'adult');
      }
      return cat === target;
    });
  }

  return missingLinks;
}

/**
 * Performs an automated or manual sync round:
 * - Selects unadded world links (batch of 3 to 8 links per round)
 * - Tags them with fresh added timestamp and badges
 * - Updates sync history and statistics
 * - Returns updated list of all links + newly added subset
 */
export function performAutoSync(
  currentLinks: LinkItem[],
  batchLimit: number = 5,
  regionFilter?: string,
  categoryFilter?: string
): {
  updatedLinks: LinkItem[];
  addedLinks: LinkItem[];
  config: AutoSyncConfig;
  message: string;
} {
  const config = getAutoSyncConfig();
  let available = getAvailableNewLinks(currentLinks);

  if (regionFilter && regionFilter !== 'all') {
    available = available.filter(
      (l) => l.regions && (l.regions.includes(regionFilter) || l.regions.includes('Global'))
    );
  }

  if (categoryFilter && categoryFilter !== 'all') {
    const target = categoryFilter.toLowerCase();
    available = available.filter((l) => {
      const cat = (l.category || '').toLowerCase();
      if (target === '18+' || target === 'adult') {
        return cat === '18+' || cat === 'adult' || (l.tags || []).some(t => t.toLowerCase() === '18+' || t.toLowerCase() === 'adult');
      }
      return cat === target;
    });
  }

  if (available.length === 0) {
    const updatedConfig: AutoSyncConfig = {
      ...config,
      lastSyncTime: Date.now(),
    };
    saveAutoSyncConfig(updatedConfig);
    const catLabel = categoryFilter && categoryFilter !== 'all' ? ` for ${getCategoryDisplayName(categoryFilter)}` : '';
    return {
      updatedLinks: currentLinks,
      addedLinks: [],
      config: updatedConfig,
      message: `All verified links${catLabel} are currently up to date! (सभी लिंक्स नवीनतम हैं)`,
    };
  }

  // Pick the next batch of links
  const toAdd = available.slice(0, batchLimit).map((link) => {
    const migrated = migrateLink(link);
    const badges = getLinkBadges(migrated);
    return {
      ...migrated,
      badge: badges[0] || 'Free',
      badges: badges,
      addedAt: new Date().toISOString(),
    };
  });

  const merged = deduplicateLinks([...toAdd, ...currentLinks]);
  const sampleTitles = toAdd.map((l) => l.title);
  const affectedRegions = Array.from(new Set(toAdd.flatMap((l) => l.regions || ['Global'])));
  const affectedCategories = Array.from(new Set(toAdd.map((l) => l.category)));

  // Detailed records for history
  const linkRecords: AutoAddedLinkRecord[] = toAdd.map((l) => ({
    id: l.id,
    title: l.title,
    url: l.url,
    domain: l.domain,
    category: l.category,
    categoryName: getCategoryDisplayName(l.category),
    regions: l.regions || ['Global'],
    badge: l.badge,
    description: l.description,
    addedAt: l.addedAt || new Date().toISOString(),
    timestamp: Date.now(),
  }));

  const historyEntry: AutoSyncHistoryEntry = {
    id: `sync-${Date.now()}`,
    timestamp: Date.now(),
    count: toAdd.length,
    regions: affectedRegions,
    categories: affectedCategories,
    links: linkRecords,
  };

  const existingAllRecords = config.allAutoAddedLinks || [];
  const existingRecordIds = new Set(existingAllRecords.map((r) => r.id));
  const newAllRecords = [
    ...linkRecords.filter((r) => !existingRecordIds.has(r.id)),
    ...existingAllRecords,
  ].slice(0, 100);

  const updatedConfig: AutoSyncConfig = {
    ...config,
    lastSyncTime: Date.now(),
    totalAutoAdded: config.totalAutoAdded + toAdd.length,
    syncHistory: [
      historyEntry,
      ...config.syncHistory.slice(0, 19),
    ],
    allAutoAddedLinks: newAllRecords,
  };

  saveAutoSyncConfig(updatedConfig);

  const regionSummary = affectedRegions.slice(0, 3).join(', ');
  const message = `✨ Auto-Added ${toAdd.length} new verified links (${sampleTitles.slice(0, 2).join(', ')}...) into ${toAdd.map(l => getCategoryDisplayName(l.category)).filter((v, i, a) => a.indexOf(v) === i).join(', ')}!`;

  return {
    updatedLinks: merged,
    addedLinks: toAdd,
    config: updatedConfig,
    message,
  };
}

/**
 * Clears auto-sync link history.
 */
export function clearAutoSyncHistory(): AutoSyncConfig {
  const config = getAutoSyncConfig();
  const resetConfig: AutoSyncConfig = {
    ...config,
    syncHistory: [],
    allAutoAddedLinks: [],
  };
  saveAutoSyncConfig(resetConfig);
  return resetConfig;
}

/**
 * Intelligent startup check: Runs automatically when user opens the app if enabled.
 */
export function checkAndRunStartupAutoSync(
  currentLinks: LinkItem[]
): { updatedLinks: LinkItem[]; addedLinks: LinkItem[]; message?: string } | null {
  const config = getAutoSyncConfig();
  if (!config.isEnabled) return null;

  const now = Date.now();
  const timeSinceLastSync = now - config.lastSyncTime;

  // If startup or time elapsed > 10 minutes, pull new links
  const shouldSync = config.lastSyncTime === 0 || timeSinceLastSync > 10 * 60 * 1000;

  if (shouldSync) {
    const available = getAvailableNewLinks(currentLinks);
    if (available.length > 0) {
      const result = performAutoSync(currentLinks, 4);
      if (result.addedLinks.length > 0) {
        return {
          updatedLinks: result.updatedLinks,
          addedLinks: result.addedLinks,
          message: result.message,
        };
      }
    }
  }

  return null;
}
